# Generated by Django 6.1 on 2026-08-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catalog",
            new_name="Category",
        ),
    ]
