# Generated by Django 6.1 on 2026-08-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_rename_catalog_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
    ]
